# Generated by Django 4.2.1 on 2023-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_teamassignment_notify_via_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamassignment",
            old_name="notify_via_email",
            new_name="notify_via_email_high_priority",
        ),
        migrations.RenameField(
            model_name="teamassignment",
            old_name="notify_via_phone",
            new_name="notify_via_phone_high_priority",
        ),
        migrations.RenameField(
            model_name="teamassignment",
            old_name="notify_via_webhooks",
            new_name="notify_via_phone_low_priority",
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="availability",
            field=models.CharField(
                choices=[("available", "available"), ("away", "away")],
                default="available",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="notify_via_email_low_priority",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="notify_via_webhooks_high_priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="notify_via_webhooks_low_priority",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="status",
            field=models.CharField(default="on standby⚡", max_length=255),
        ),
    ]
