# Generated by Django 4.2 on 2023-04-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_subscriber_subscriberassignment_subscriber_monitors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="monitors",
        ),
        migrations.RemoveField(
            model_name="subscriberassignment",
            name="monitor",
        ),
        migrations.RemoveField(
            model_name="subscriberassignment",
            name="subscriber",
        ),
        migrations.RemoveField(
            model_name="user",
            name="monitors",
        ),
        migrations.DeleteModel(
            name="MonitorAssignment",
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
        migrations.DeleteModel(
            name="SubscriberAssignment",
        ),
    ]
