# Generated by Django 4.2.1 on 2023-05-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0004_rename_notify_via_email_teamassignment_notify_via_email_high_priority_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="untitled", max_length=255)),
                ("description", models.CharField(default="untitled", max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.usergroups",
            ),
        ),
    ]
