# Generated by Django 4.2 on 2023-04-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_guest_remove_subscriber_monitors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamassignment",
            old_name="can_add_teammate",
            new_name="is_member",
        ),
        migrations.RemoveField(
            model_name="teamassignment",
            name="can_remove_teammate",
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="is_billing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamassignment",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
