version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  redis:
    image: redis:6.2

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - elasticsearch
      - redis

  celery:
    build: .
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - elasticsearch
      - redis

  celerybeat:
    build: .
    command: celery -A myproject beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - elasticsearch
      - redis
