# Generated by Django 4.2 on 2023-04-23 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout', models.PositiveIntegerField(default=5)),
                ('last_checked', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('test_uptime', models.BooleanField(default=False)),
                ('test_port', models.BooleanField(default=False)),
                ('test_ssl', models.BooleanField(default=False)),
                ('test_speed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField()),
                ('status_code', models.PositiveIntegerField()),
                ('log', models.TextField()),
                ('checked_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('Uptime Monitor Result', 'Uptime Monitor Result'), ('Port Monitor Result', 'Port Monitor Result'), ('SSL Monitor Result', 'SSL Monitor Result'), ('Speed Monitor Result', 'Speed Monitor Result')], max_length=255)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitor.monitor')),
            ],
        ),
    ]
