# Generated by Django 4.2 on 2023-04-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitorresult",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitorresult",
            name="log",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitorresult",
            name="response_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitorresult",
            name="status_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
