# Generated by Django 4.2 on 2023-04-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_alter_monitorresult_checked_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitor",
            name="test_port",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="test_speed",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="test_ssl",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="test_uptime",
        ),
        migrations.RemoveField(
            model_name="monitor",
            name="url",
        ),
        migrations.AddField(
            model_name="monitor",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("30", "30 Seconds"),
                    ("60", "1 Minute"),
                    ("300", "5 Minutes"),
                    ("1800", "30 Minutes"),
                    ("3600", "1 Hour"),
                    ("21600", "6 Hour"),
                ],
                default=30,
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="ip",
            field=models.GenericIPAddressField(default="127.0.0.1"),
        ),
        migrations.AddField(
            model_name="monitor",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="monitor",
            name="protocol",
            field=models.CharField(
                choices=[("HTTP", "HTTP"), ("HTTPS", "HTTPS"), ("ICMP", "ICMP")],
                default="HTTPS",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="regex",
            field=models.CharField(default="200", max_length=25),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="last_checked",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
