# Generated by Django 4.2 on 2023-04-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0003_remove_monitor_test_port_remove_monitor_test_speed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="region_Asia1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitor",
            name="region_EU1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitor",
            name="region_US1",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monitor",
            name="region_US2",
            field=models.BooleanField(default=False),
        ),
    ]
