# Generated by Django 4.2 on 2023-04-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0004_monitor_region_asia1_monitor_region_eu1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitorresult",
            name="log",
        ),
        migrations.RemoveField(
            model_name="monitorresult",
            name="status_code",
        ),
        migrations.RemoveField(
            model_name="monitorresult",
            name="type",
        ),
        migrations.AddField(
            model_name="monitorresult",
            name="connection_time",
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="monitorresult",
            name="dns_lookup_time",
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="monitorresult",
            name="ssl_handshake_time",
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="monitorresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("OK", "Status OK"),
                    ("Down", "Status DOWN"),
                    ("Unknown", "Unreachable"),
                ],
                default="Unknown",
                max_length=255,
            ),
        ),
    ]
