# Generated by Django 4.2 on 2023-04-28 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_can_add_teammate_teamassignment_is_member_and_more"),
        (
            "monitor",
            "0006_subscriberassignment_guestassignment_monitor_guests_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="monitor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitor",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.team",
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="tags",
            field=models.ManyToManyField(related_name="monitors", to="monitor.tags"),
        ),
    ]
