# Generated by Django 4.2 on 2023-05-02 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0007_tags_monitor_description_monitor_team_monitor_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=500, null=True)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("token", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="monitor",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitor",
            name="credentials",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitor",
                to="monitor.credentials",
            ),
        ),
    ]
