# Generated by Django 4.2 on 2023-05-02 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0008_credentials_monitor_is_public_monitor_credentials"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="credentials",
            managers=[],
        ),
    ]
