# Generated by Django 4.2 on 2023-05-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_can_add_teammate_teamassignment_is_member_and_more"),
        ("monitor", "0010_alter_monitor_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="confirmation_period",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="monitor",
            name="hostname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="monitor",
            name="log_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitor",
            name="recovery_period",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("30", "30 Seconds"),
                    ("60", "1 Minute"),
                    ("300", "5 Minutes"),
                    ("1800", "30 Minutes"),
                    ("3600", "1 Hour"),
                    ("21600", "6 Hour"),
                    ("43200", "12 Hour"),
                    ("64800", "18 Hour"),
                    ("86400", "1 Day"),
                    ("259200", "3 Day"),
                    ("604800", "7 Day"),
                ],
                default=30,
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="regex",
            field=models.CharField(default="200", max_length=250),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="tags",
            field=models.ManyToManyField(related_name="monitors", to="monitor.tags"),
        ),
        migrations.CreateModel(
            name="DomainExpiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=750)),
                ("expires_on", models.DateTimeField()),
                ("registered_on", models.DateField()),
                ("updated_on", models.DateTimeField()),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.team",
                    ),
                ),
            ],
        ),
    ]
