# Generated by Django 4.2 on 2023-05-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0012_cronmonitor_alter_monitor_frequency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("through_phone", models.BooleanField(default=False)),
                ("through_sms", models.BooleanField(default=False)),
                ("through_email", models.BooleanField(default=True)),
                ("through_notif", models.BooleanField(default=False)),
                ("through_slack", models.BooleanField(default=False)),
                ("through_hook", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="cronmonitor",
            name="alert",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.alert",
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="alert",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.alert",
            ),
        ),
    ]
