# Generated by Django 4.2 on 2023-05-04 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_rename_can_add_teammate_teamassignment_is_member_and_more"),
        ("monitor", "0013_alert_cronmonitor_alert_monitor_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="type",
            field=models.CharField(
                choices=[
                    ("Status Monitor", "Status Monitor"),
                    ("Keyword Monitor", "Keyword Monitor"),
                ],
                default="Status Monitor",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="cronmonitor",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crons",
                to="users.team",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitors",
                to="users.team",
            ),
        ),
    ]
