# Generated by Django 4.2.1 on 2023-05-05 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationlevel",
            name="users",
            field=models.ManyToManyField(
                help_text="Users to be notified for this escalation level",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
