# Generated by Django 4.2.1 on 2023-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnCallCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("timezone", models.CharField(max_length=255)),
            ],
        ),
    ]
