# Generated by Django 4.2.1 on 2023-05-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0003_oncallcalendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="MyAction", max_length=255)),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMAIL", "Send Email"),
                            ("MESSAGE", "Send Message"),
                            ("CALL", "Send a Call"),
                            ("HOOK", "Trigger a Webhook"),
                            ("JIRA", "Create an issue in JIRA"),
                            ("SLACK", "Post a message to Slack"),
                            ("LOG", "Create a log message"),
                        ],
                        default="LOG",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("context", models.TextField()),
                ("recipient", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="escalationlevel",
            name="level_number",
        ),
        migrations.RemoveField(
            model_name="escalationlevel",
            name="time_interval",
        ),
        migrations.RemoveField(
            model_name="escalationlevel",
            name="users",
        ),
        migrations.RemoveField(
            model_name="escalationpolicy",
            name="escalation_levels",
        ),
        migrations.AddField(
            model_name="escalationlevel",
            name="delay_for",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Denotes the delay in seconds between successive actions",
            ),
        ),
        migrations.AddField(
            model_name="escalationlevel",
            name="name",
            field=models.CharField(default="MyLevel", max_length=255),
        ),
        migrations.AddField(
            model_name="escalationlevel",
            name="repeat_for",
            field=models.PositiveIntegerField(
                default=0, help_text="How many times to repeat the level"
            ),
        ),
        migrations.AddField(
            model_name="escalationpolicy",
            name="delay",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="escalationpolicy",
            name="name",
            field=models.CharField(default="MyPolicy", max_length=255),
        ),
        migrations.CreateModel(
            name="EscalationLevelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.PositiveIntegerField()),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident.escalationlevel",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident.escalationpolicy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="escalationlevel",
            name="policy",
            field=models.ManyToManyField(
                help_text="Which policy is the escalation level part of",
                through="incident.EscalationLevelAssignment",
                to="incident.escalationpolicy",
            ),
        ),
    ]
