# Generated by Django 4.2.1 on 2023-05-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incident",
            "0004_escalationaction_remove_escalationlevel_level_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="escalationaction",
            old_name="recipient",
            new_name="entity",
        ),
        migrations.AddField(
            model_name="escalationaction",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("ATTRIBUTE", "Parse as Attribute"),
                    ("ID", "Parse as id"),
                    ("CS:ID", "Parse as comma-separated id"),
                    ("EMAIL", "Parse as email address"),
                    ("CS:EMAIL", "Parse as comma-separated email address"),
                    ("SMS", "Parse as SMS"),
                    ("CS:SMS", "Parse as comma-separated SMS"),
                    ("PHONE", "Parse as phone number"),
                    ("CS:PHONE", "Parse as comma-separated phone number"),
                    ("CHANNEL", "Parse as slack channel"),
                    ("CS:CHANNEL", "Parse as comma-separated slack channel"),
                    ("JIRA", "Parse as JIRA Ticket"),
                    ("HOOK", "Parse as Webhook"),
                    ("EX:HOOK", "Parse as External Webhook"),
                ],
                default="Attribute",
                max_length=255,
            ),
        ),
    ]
