# Generated by Django 4.2.1 on 2023-05-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0005_rename_recipient_escalationaction_entity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escalationlevel",
            name="policy",
            field=models.ManyToManyField(
                help_text="Which policy is the escalation level part of",
                related_name="levels",
                through="incident.EscalationLevelAssignment",
                to="incident.escalationpolicy",
            ),
        ),
    ]
