# Generated by Django 4.2.1 on 2023-05-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0006_alter_escalationlevel_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationaction",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="incident.escalationlevel",
            ),
        ),
    ]
