# Generated by Django 4.2.1 on 2023-05-11 19:55

from django.db import migrations, models
import incident.validators


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0009_delete_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationpolicy",
            name="max_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="escalationpolicy",
            name="notify_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="oncallcalendar",
            name="timezone",
            field=models.CharField(
                max_length=255, validators=[incident.validators.validate_timezone]
            ),
        ),
        migrations.AlterField(
            model_name="oncallcalendar",
            name="url",
            field=models.URLField(
                validators=[incident.validators.validate_icalendar_url]
            ),
        ),
    ]
