# Generated by Django 4.2.1 on 2023-05-16 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0011_webhook_remove_escalationaction_context_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escalationaction",
            name="intent",
        ),
    ]
