# Generated by Django 4.2.1 on 2023-05-04 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("logger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="guestassignment",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="logger.endpoint"
            ),
        ),
        migrations.AddField(
            model_name="guestassignment",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.guest"
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="guests",
            field=models.ManyToManyField(
                related_name="endpoints",
                through="logger.GuestAssignment",
                to="users.guest",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="request_handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="logger.requesthandler",
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="endpoints",
                through="logger.SubscriberAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cronsubscriberassignment",
            name="cron",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="logger.cronhandler"
            ),
        ),
        migrations.AddField(
            model_name="cronsubscriberassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cronhandler",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="crons",
                through="logger.CronSubscriberAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
