# Generated by Django 4.2 on 2023-05-04 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logger_type",
                    models.CharField(
                        choices=[("cron", "CRON Monitor"), ("hook", "Hook Monitor")],
                        max_length=255,
                    ),
                ),
                ("url", models.URLField()),
                ("name", models.CharField(default="Logger", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("push_email", models.BooleanField(default=True)),
                ("push_sms", models.BooleanField(default=False)),
                ("push_call", models.BooleanField(default=False)),
                ("push_notif", models.BooleanField(default=False)),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(30)],
                    ),
                ),
                ("confirmation_period", models.PositiveIntegerField(default=0)),
                ("escalation_period", models.PositiveIntegerField(default=5)),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="endpoint",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
