# Generated by Django 4.2 on 2023-05-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0002_cronhandler_endpoint_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="regions",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="request_handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="logger.requesthandler",
            ),
        ),
    ]
