# Generated by Django 4.2.1 on 2023-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="is_public",
        ),
        migrations.AddField(
            model_name="service",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
