# Generated by Django 4.2.1 on 2023-05-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="cronhandler",
            name="collection",
            field=models.ManyToManyField(related_name="crons", to="logger.collection"),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="collection",
            field=models.ManyToManyField(
                related_name="endpoints", to="logger.collection"
            ),
        ),
    ]
