# Generated by Django 4.2.1 on 2023-05-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("incident", "0001_initial"),
        ("logger", "0003_collection_cronhandler_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="escalation_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="incident.escalationpolicy",
            ),
        ),
    ]
