# Generated by Django 4.2 on 2023-05-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0004_alter_endpoint_regions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesthandler",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requesthandler",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
