# Generated by Django 4.2.1 on 2023-05-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0004_collection_escalation_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="regions",
            field=models.TextField(blank=True),
        ),
    ]
