# Generated by Django 4.2.1 on 2023-05-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0005_alter_endpoint_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_paused",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cronhandler",
            name="is_paused",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="is_paused",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="timeout",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="requesthandler",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
