# Generated by Django 4.2.1 on 2023-05-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0006_collection_is_paused_cronhandler_is_paused_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="regions",
        ),
        migrations.AddField(
            model_name="endpoint",
            name="is_au",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="is_eu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="is_sn",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="is_us",
            field=models.BooleanField(default=True),
        ),
    ]
