# Generated by Django 4.2.1 on 2023-05-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0006_alter_endpoint_check_frequency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintainancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="requesthandler",
            name="headers",
        ),
        migrations.AddField(
            model_name="requesthandler",
            name="header_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="requesthandler",
            name="header_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="requesthandler",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="maintainance_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="logger.maintainancepolicy",
            ),
        ),
    ]
