# Generated by Django 4.2.1 on 2023-05-04 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0007_remove_endpoint_regions_endpoint_is_au_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="is_paused",
        ),
        migrations.RemoveField(
            model_name="cronhandler",
            name="is_paused",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="is_paused",
        ),
    ]
