# Generated by Django 4.2.1 on 2023-05-09 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0007_maintainancepolicy_remove_requesthandler_headers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="push_call",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="push_email",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="push_notif",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="push_sms",
        ),
    ]
