# Generated by Django 4.2.1 on 2023-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logger",
            "0008_remove_endpoint_push_call_remove_endpoint_push_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cronhandler",
            name="token",
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
    ]
