# Generated by Django 4.2.1 on 2023-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0009_cronhandler_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="verify_ssl",
        ),
        migrations.AddField(
            model_name="requesthandler",
            name="verify_ssl",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="requesthandler",
            name="method",
            field=models.CharField(
                choices=[
                    ("HEAD", "HEAD"),
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                ],
                default="GET",
                max_length=5,
            ),
        ),
    ]
