# Generated by Django 4.2.1 on 2023-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "logger",
            "0010_remove_endpoint_verify_ssl_requesthandler_verify_ssl_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="logger_type",
            field=models.CharField(
                choices=[
                    ("status", "Status Monitor"),
                    ("keyword", "Keyword Monitor"),
                    ("ping", "Ping Monitor"),
                    ("tcp", "TCP Monitor"),
                    ("udp", "UDP Monitor"),
                    ("smtp", "SMTP Monitor"),
                    ("pop", "POP Monitor"),
                    ("imap", "IMAP Monitor"),
                ],
                default="status",
                max_length=255,
            ),
        ),
    ]
