# Generated by Django 4.2.1 on 2023-05-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("logger", "0011_alter_endpoint_logger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("coupled", "coupled"), ("decoupled", "decoupled")],
                default="decoupled",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP", "marks status as UP"),
                            ("DOWN", "marks status as DOWN"),
                        ],
                        default="UP",
                        max_length=4,
                    ),
                ),
                (
                    "response_time",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
