# Generated by Django 4.2.1 on 2023-05-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0014_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="trigger_type",
        ),
        migrations.AddField(
            model_name="events",
            name="request_handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="logger.requesthandler",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
