# Generated by Django 4.2.1 on 2023-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0015_remove_events_trigger_type_events_request_handler_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="incident",
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="check_frequency",
            field=models.PositiveIntegerField(
                choices=[
                    (30, "30 seconds"),
                    (45, "45 seconds"),
                    (60, "1 minute"),
                    (120, "2 minutes"),
                    (180, "3 minutes"),
                    (300, "5 minutes"),
                    (600, "10 minutes"),
                    (900, "15 minutes"),
                    (1800, "30 minutes"),
                ],
                default=180,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[("P1", "P1"), ("P2", "P2"), ("P3", "P3"), ("P4", "P4")],
                default="P1",
                max_length=20,
            ),
        ),
    ]
