# Generated by Django 4.2.1 on 2023-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0016_remove_log_incident_alter_endpoint_check_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low Priority Incidents"),
                    ("High", "High Priority Incidents"),
                ],
                default="Low",
                max_length=20,
            ),
        ),
    ]
