# Generated by Django 4.2.1 on 2023-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0017_alter_incident_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="source",
            field=models.ImageField(
                blank=True,
                help_text="store the image of the resource",
                null=True,
                upload_to="media/archive/",
            ),
        ),
    ]
