# Generated by Django 4.2.1 on 2023-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0018_incident_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="escalation_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
