# Generated by Django 4.2.1 on 2023-05-16 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logger", "0019_incident_escalation_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Events",
        ),
    ]
